# Generated by Django 4.0 on 2022-06-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='graduação')),
                ('posto', models.CharField(blank=True, max_length=50, null=True, verbose_name='posto')),
            ],
        ),
        migrations.AddField(
            model_name='escala',
            name='data_final',
            field=models.DateField(help_text='Data no Formato dd/mm/YYYY', null=True, verbose_name='data final'),
        ),
        migrations.AddField(
            model_name='escala',
            name='data_inicio',
            field=models.DateField(help_text='Data no Formato dd/mm/YYYY', null=True, verbose_name='data inicial'),
        ),
        migrations.AddField(
            model_name='escala',
            name='hora_final',
            field=models.TimeField(null=True, verbose_name='hora final'),
        ),
        migrations.AddField(
            model_name='escala',
            name='hora_inicial',
            field=models.TimeField(null=True, verbose_name='hora inicial'),
        ),
        migrations.AddField(
            model_name='policial',
            name='cpf',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='cpf'),
        ),
        migrations.AddField(
            model_name='policial',
            name='rg_militar',
            field=models.IntegerField(null=True, unique=True, verbose_name='rg'),
        ),
        migrations.AddField(
            model_name='policial',
            name='sobrenome',
            field=models.CharField(max_length=50, null=True, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='policial',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='nome'),
        ),
    ]
