# Generated by Django 4.0 on 2022-07-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_escala_horas_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='policial',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='core.policial'),
            preserve_default=False,
        ),
    ]
