# Generated by Django 4.0 on 2022-07-01 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_escala_policial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escala',
            old_name='policial',
            new_name='cpf',
        ),
    ]
