# Generated by Django 4.0 on 2022-07-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_policial_escala_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='rg_militar',
            field=models.IntegerField(null=True, unique=True, verbose_name='rg militar'),
        ),
    ]
