# Generated by Django 4.0 on 2022-07-01 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_policial_rg_militar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escala',
            old_name='cpf',
            new_name='Policial',
        ),
    ]
