# Generated by Django 4.0 on 2022-07-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_cpf_escala_policial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_militar', models.IntegerField(null=True, unique=True, verbose_name='rg militar')),
                ('cpf', models.CharField(max_length=15, null=True, unique=True, verbose_name='cpf')),
            ],
        ),
        migrations.CreateModel(
            name='Graduação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='graduação')),
            ],
        ),
        migrations.RemoveField(
            model_name='escala',
            name='Policial',
        ),
        migrations.RemoveField(
            model_name='policial',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='policial',
            name='rg_militar',
        ),
        migrations.RemoveField(
            model_name='posto',
            name='graduacao',
        ),
    ]
