# Generated by Django 4.0 on 2022-07-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_documents_graduação_remove_escala_policial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policial',
            name='Documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documents', verbose_name='documentos'),
        ),
    ]
