# Generated by Django 4.0 on 2022-07-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_policial_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='VTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, verbose_name='placa')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='codigo')),
            ],
        ),
        migrations.RenameModel(
            old_name='Graduação',
            new_name='Graduacao',
        ),
        migrations.RemoveField(
            model_name='policial',
            name='Documents',
        ),
        migrations.AddField(
            model_name='escala',
            name='Policial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.policial', verbose_name='policial'),
        ),
        migrations.AddField(
            model_name='escala',
            name='semana',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terça', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='segunda', max_length=50, verbose_name='semana'),
        ),
        migrations.AddField(
            model_name='policial',
            name='Graduacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.graduacao', verbose_name='graduação'),
        ),
        migrations.AddField(
            model_name='policial',
            name='Posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.posto', verbose_name='posto'),
        ),
        migrations.AddField(
            model_name='policial',
            name='cpf',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='cpf'),
        ),
        migrations.AddField(
            model_name='policial',
            name='rg_militar',
            field=models.IntegerField(null=True, unique=True, verbose_name='rg militar'),
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.AddField(
            model_name='escala',
            name='VTR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vtr', verbose_name='VTR'),
        ),
    ]
