# Generated by Django 4.0 on 2022-07-01 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vtr_rename_graduação_graduacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduacao',
            options={'ordering': ('graduacao',), 'verbose_name': 'graduação', 'verbose_name_plural': 'graduações'},
        ),
    ]
