# Generated by Django 4.0 on 2022-07-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_graduacao_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escala',
            old_name='Policial',
            new_name='policial',
        ),
        migrations.RenameField(
            model_name='escala',
            old_name='VTR',
            new_name='vtr',
        ),
        migrations.RenameField(
            model_name='policial',
            old_name='Graduacao',
            new_name='graduacao',
        ),
        migrations.RenameField(
            model_name='policial',
            old_name='Posto',
            new_name='posto',
        ),
        migrations.AlterField(
            model_name='vtr',
            name='codigo',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='codigo'),
        ),
    ]
