# Generated by Django 4.0 on 2022-07-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_policial_escala_policial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='horas_total',
            field=models.IntegerField(null=True, verbose_name='horas'),
        ),
    ]
