# Generated by Django 4.0 on 2022-07-02 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_escala_horas_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='policial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.policial', verbose_name='policial'),
        ),
        migrations.AlterField(
            model_name='vtr',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, verbose_name='codigo'),
        ),
    ]
