# Generated by Django 4.0 on 2022-07-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_escala_policial_alter_vtr_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(blank=True, max_length=20, null=True, verbose_name='funcao')),
            ],
        ),
        migrations.AddField(
            model_name='escala',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.funcao', verbose_name='funções'),
        ),
    ]
