# Generated by Django 4.0 on 2022-07-03 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_funcao_escala_funcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='policial',
        ),
        migrations.AddField(
            model_name='policial',
            name='escala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas', to='core.escala', verbose_name='escala'),
        ),
    ]
