# Generated by Django 4.0 on 2022-07-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_escala_policial_policial_escala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policial',
            name='escala',
        ),
        migrations.CreateModel(
            name='EscalaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policiais', to='core.escala', verbose_name='escala')),
                ('policial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policiais', to='core.policial', verbose_name='policial')),
            ],
        ),
    ]
