# Generated by Django 4.0 on 2022-07-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_policial_escala_escalaregistro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posto',
            options={'ordering': ('posto',), 'verbose_name': 'posto', 'verbose_name_plural': 'postos'},
        ),
    ]
