# Generated by Django 4.0 on 2022-09-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_posto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacao',
            name='graduacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='graduaçao'),
        ),
        migrations.AlterField(
            model_name='policial',
            name='graduacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.graduacao'),
        ),
        migrations.AlterField(
            model_name='policial',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.posto'),
        ),
    ]
