# Generated by Django 4.0 on 2023-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_graduacao_graduacao_alter_policial_graduacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='rg_militar',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='rg militar'),
        ),
    ]
